### ISSUE TITLE
Update aws-java-sdk.version

### ISSUE THREAD

**Issue by destebanm** [Lightstreamer/cloudwatch-logback-appender#1]
Hi!
In one of its updates, Amazon deprecated some methods related with its clients.
In your last version library available in maven central (0.10.1) I see that you are using AWS 1.11.52.

Will you plan to update it?

Thank you!

**Comment by fvasco** [comment]
Hi.

Cloudwatch appender work with 1.11.52 version and should work with any 1.11.x version.

You can use preferred aws-java-sdk-logs version, you must prepend this dependency before Appender's one in your pom.xml, ie:

        <dependency>
            <artifactId>aws-java-sdk-logs</artifactId>
        ...
        </dependency>
        <dependency>
            <artifactId>cloudwatch-logback-appender</artifactId>
        ...
        </dependency>

Finally we will glad to accept a pull request ;)

**Comment by destebanm** [comment]
OK, thanks!
